### ISSUE TITLE
When the output size is different from the input ,the result is wrong

### ISSUE THREAD

**Issue by flazerain** [wuneng/WarpAffine2GridSample#3]
the code: 

```
...
cv_img = cv2.warpAffine(image, M, (112, 112))
...
theta = normalize_transforms(param[0:2,:], w, h)
...
grid = F.affine_grid(theta, [1,3,112,112])
tensor_img = F.grid_sample(tensor_img, grid)
...
```

the affine_grid result is wrong.

**Comment by wuneng** [comment]
`theta = normalize_transforms(param[0:2,:], 112,112)` should get an expected result.

**Comment by twmht** [comment]
@wuneng 

what is normalize_transforms do?

**Comment by twmht** [comment]
@wuneng 

it can't work when input size is different with output size, do you have any idea?

**Comment by wuneng** [comment]
@twmht  You can send your example code to me through email, 6553947@qq.com.  I will check it.

**Comment by wuneng** [comment]
@twmht   Bug have be solved.  Have a try.
